config/routes.rb
Rails.application.routes.draw do

  resources :expense_categories

  resources :expenses do
    resources :expense_categories do
    end
  end



  resources :invoices do
    resources :invoice_line_items 
  end
    



  resources :invoice_line_items
  resources :taxes

  resources :items do
    collection do
      post 'load_item_data'
      get 'duplicate_item'
    end
  end

  resources :contacts do
  end


  devise_for :users

  resources :companies do
    collection do
      post 'get_contacts_and_items'
    end
  end

  root 'welcome#index'


  devise_scope :user do
        get '/users/sign_out' => 'devise/sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get ':controller(/:action(/:id))(.:format)'

end
end

app/models/company.rb
class Company < ApplicationRecord

  scope :multiple, lambda { |ids_list| where("id in (?)", ids_list.is_a?(String) ? ids_list.split(',') : [*ids_list]) }

  belongs_to :user, optional: true
  has_many :contacts
  has_many :items
  has_many :taxes  
  has_many :invoices
  has_many :expenses



  mount_uploader :companylogo, CompanylogoUploader
  acts_as_archival
  acts_as_paranoid

  def self.filter(params)
    mappings = {active: 'unarchived', archived: 'archived', deleted: 'only_deleted'}
    method = mappings[params[:status].to_sym]
    params[:account].companies.send(method).page(params[:page]).per(params[:per])
  end

  def self.recover_archived(ids)
    multiple(ids).map(&:unarchive)
  end

  def self.recover_deleted(ids)
    multiple(ids).only_deleted.each { |company| company.restore; company.unarchive }
  end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  include CompaniesHelper
  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.companies

    respond_to do |format|
      format.html
      format.json { render json: @companies }
      format.js
  end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = current_user.companies.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @company }
  end
  end

  # GET /companies/new
  def new
    @company = Company.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = current_user.companies.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = current_user.companies.build(company_params)

    respond_to do |format|
      if @company.save
	CompanyMailer.added_company(@company).deliver
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company = current_user.companies.find(params[:id])
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = current_user.companies.find(params[:id])
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def filter_companies
    @companies = Company.filter(params.merge(per: session["#{controller_name}-per_page"], user: current_user)).order(sort_column + " " + sort_direction)
    respond_to { |format| format.js }
  end

  def select
    session['current_company'] = params[:id]
    current_user.update_attributes(current_company: params[:id])
    company =  Company.find(params[:id])
    render :text => company.company_name
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name, :company_contact_name, :contact_title, :company_country, :company_city, :company_street_address_1, :company_street_address_2, :company_state, :company_zipcode, :company_phone_number, :company_email, :company_cin, :company_vat, :bank_info, :companylogo, :company_tag_line, :companywebsite)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => {:novalidate => "", :multipart => true} do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </div>

  <div class="field">
    <%= f.label :company_contact_name %>
    <%= f.text_field :company_contact_name %>
  </div>

  <div class="field">
    <%= f.label :contact_title %>
    <%= f.text_field :contact_title %>
  </div>

  <div class="field">
    <%= f.label :company_country %>
    <%= f.text_field :company_country %>
  </div>

  <div class="field">
    <%= f.label :company_city %>
    <%= f.text_field :company_city %>
  </div>

  <div class="field">
    <%= f.label :company_street_address_1 %>
    <%= f.text_field :company_street_address_1 %>
  </div>

  <div class="field">
    <%= f.label :company_street_address_2 %>
    <%= f.text_field :company_street_address_2 %>
  </div>

  <div class="field">
    <%= f.label :company_state %>
    <%= f.text_field :company_state %>
  </div>

  <div class="field">
    <%= f.label :company_zipcode %>
    <%= f.text_field :company_zipcode %>
  </div>

  <div class="field">
    <%= f.label :company_phone_number %>
    <%= f.text_field :company_phone_number %>
  </div>

  <div class="field">
    <%= f.label :company_email %>
    <%= f.text_field :company_email %>
  </div>

  <div class="field">
    <%= f.label :company_cin %>
    <%= f.text_field :company_cin %>
  </div>

  <div class="field">
    <%= f.label :company_vat %>
    <%= f.text_field :company_vat %>
  </div>

  <div class="field">
    <%= f.label :bank_info %>
    <%= f.text_area :bank_info, :placeholder => "Bank Info for your customer to enable him to Bank transfer Payment. Will be printed in Invoice", :class => 'col-md-6', :rows => '3' %>
  </div>

  <div class="field">
    <%= f.label :companylogo %>
    <%= image_tag(@company.companylogo_url) if @company.companylogo? %>
    <%= f.file_field :companylogo %>
    <%= f.hidden_field :companylogo_cache %>
  </div>

  <div class="field">
    <%= f.label :company_tag_line %>
    <%= f.text_field :company_tag_line %>
  </div>

  <div class="field">
    <%= f.label :companywebsite %>
    <%= f.text_field :companywebsite %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Company contact name</th>
      <th>Contact title</th>
      <th>Company country</th>
      <th>Company city</th>
      <th>Company street address 1</th>
      <th>Company street address 2</th>
      <th>Company state</th>
      <th>Company zipcode</th>
      <th>Company phone number</th>
      <th>Company email</th>
      <th>Company cin</th>
      <th>Company vat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.company_name %></td>
        <td><%= company.company_contact_name %></td>
        <td><%= company.contact_title %></td>
        <td><%= company.company_country %></td>
        <td><%= company.company_city %></td>
        <td><%= company.company_street_address_1 %></td>
        <td><%= company.company_street_address_2 %></td>
        <td><%= company.company_state %></td>
        <td><%= company.company_zipcode %></td>
        <td><%= company.company_phone_number %></td>
        <td><%= company.company_email %></td>
        <td><%= company.company_cin %></td>
        <td><%= company.company_vat %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @company.company_name %>
</p>

<p>
  <strong>Company contact name:</strong>
  <%= @company.company_contact_name %>
</p>

<p>
  <strong>Contact title:</strong>
  <%= @company.contact_title %>
</p>

<p>
  <strong>Company country:</strong>
  <%= @company.company_country %>
</p>

<p>
  <strong>Company city:</strong>
  <%= @company.company_city %>
</p>

<p>
  <strong>Company street address 1:</strong>
  <%= @company.company_street_address_1 %>
</p>

<p>
  <strong>Company street address 2:</strong>
  <%= @company.company_street_address_2 %>
</p>

<p>
  <strong>Company state:</strong>
  <%= @company.company_state %>
</p>

<p>
  <strong>Company zipcode:</strong>
  <%= @company.company_zipcode %>
</p>

<p>
  <strong>Company phone number:</strong>
  <%= @company.company_phone_number %>
</p>

<p>
  <strong>Company email:</strong>
  <%= @company.company_email %>
</p>

<p>
  <strong>Company cin:</strong>
  <%= @company.company_cin %>
</p>

<p>
  <strong>Company vat:</strong>
  <%= @company.company_vat %>
</p>

<p>
  <strong>Company Bank Account Details:</strong>(for helping your client trafer money directly to your bank account)
  <%= @company.bank_info %>
</p>

<p>
  <strong> company logo</strong>
  <%= image_tag(@company.companylogo_url(:thumb).to_s) %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>