config/routes.rb
Rails.application.routes.draw do

  resources :expense_categories

  resources :expenses do
    resources :expense_categories do
    end
  end



  resources :invoices do
    resources :invoice_line_items 
  end
    



  resources :invoice_line_items
  resources :taxes

  resources :items do
    collection do
      post 'load_item_data'
      get 'duplicate_item'
    end
  end

  resources :contacts do
  end


  devise_for :users

  resources :companies do
    collection do
      post 'get_contacts_and_items'
    end
  end

  root 'welcome#index'


  devise_scope :user do
        get '/users/sign_out' => 'devise/sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get ':controller(/:action(/:id))(.:format)'

end
end

app/models/invoice_line_item.rb
class InvoiceLineItem < ApplicationRecord

  belongs_to :item, optional: true
  belongs_to :tax1, :foreign_key => 'tax_1', :class_name => 'Tax'
  belongs_to :tax2, :foreign_key => 'tax_2', :class_name => 'Tax'
  belongs_to :invoice, optional: true

  acts_as_archival
  acts_as_paranoid

  attr_accessor :tax_one, :tax_two

  def unscoped_item
    Item.unscoped.find_by_id self.item_id
  end

end

app/controllers/invoice_line_items_controller.rb
class InvoiceLineItemsController < ApplicationController
  before_action :set_invoice_line_item, only: [:show, :edit, :update, :destroy]

  # GET /invoice_line_items
  # GET /invoice_line_items.json
  def index
    @invoice_line_items = InvoiceLineItem.all
  end

  # GET /invoice_line_items/1
  # GET /invoice_line_items/1.json
  def show
    @invoice_line_item = InvoiceLineItem.find(params[:id])
  end

  # GET /invoice_line_items/new
  def new
    @invoice_line_item = InvoiceLineItem.new
  end

  # GET /invoice_line_items/1/edit
  def edit
    @invoice_line_item = InvoiceLineItem.find(params[:id])
  end

  # POST /invoice_line_items
  # POST /invoice_line_items.json
  def create
    @invoice_line_item = InvoiceLineItem.new(invoice_line_item_params)

    respond_to do |format|
      if @invoice_line_item.save
        format.html { redirect_to @invoice_line_item, notice: 'Invoice line item was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_line_item }
      else
        format.html { render :new }
        format.json { render json: @invoice_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_line_items/1
  # PATCH/PUT /invoice_line_items/1.json
  def update
    @invoice_line_item = InvoiceLineItem.find(params[:id])
    respond_to do |format|
      if @invoice_line_item.update(invoice_line_item_params)
        format.html { redirect_to @invoice_line_item, notice: 'Invoice line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_line_item }
      else
        format.html { render :edit }
        format.json { render json: @invoice_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_line_items/1
  # DELETE /invoice_line_items/1.json
  def destroy
    @invoice_line_item = InvoiceLineItem.find(params[:id])
    @invoice_line_item.destroy
    respond_to do |format|
      format.html { redirect_to invoice_line_items_url, notice: 'Invoice line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_line_item
      @invoice_line_item = InvoiceLineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_line_item_params
      params.require(:invoice_line_item).permit(:item_name, :item_description, :item_unit_cost, :itam_quantity, :gross_line_total, :discount_amount, :tax_1, :tax_2, :created_at, :updated_at, :item_id, :invoice_id, :archive_number, :archived_at, :deleted_at, :item_quantity, :taxamountone, :taxtypeone, :taxrateone, :taxamounttwo, :taxratetwo, :taxtypetwo, :net_total, :subtotal, :shippingcharge, :invoicetotal)
    end
end

app/helpers/invoice_line_items_helper.rb
module InvoiceLineItemsHelper
end

app/views/invoice_line_items/_form.html.erb
<%= form_for(@invoice_line_item) do |f| %>
  <% if @invoice_line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice_line_item.errors.count, "error") %> prohibited this invoice_line_item from being saved:</h2>

      <ul>
      <% @invoice_line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :item_id, "Item id" %>
      <br/>
      <%= f.number_field :item_id %>
      <%= collection_select :invoice_line_item, :item_id, Item.all, :id, :item_name, :prompt => "Select an item" %>
    </div>

  <div class="field">
    <%= f.label :item_name %>
    <%= f.text_field :item_name %>
  </div>

  <div class="field">
    <%= f.label :item_description %>
    <%= f.text_field :item_description %>
  </div>

  <div class="field">
    <%= f.label :item_unit_cost %>
    <%= f.text_field :item_unit_cost %>
  </div>

  <div class="field">
    <%= f.label :item_quantity %>
    <%= f.text_field :item_quantity %>
  </div>

  <div class="field">
    <%= f.label :gross_line_total %>
    <%= f.text_field :gross_line_total %>
  </div>

  <div class="field">
    <%= f.label :discount_amount %>
    <%= f.text_field :discount_amount %>
  </div>

  <div class="field">
    <%= f.label :net_total %>
    <%= f.text_field :net_total %>
  </div>

  <div class="field">
    <%= f.label :taxtypeone %>
    <%= f.text_field :taxtypeone %>
  </div>

  <div class="field">
    <%= f.label :taxrateone %>
    <%= f.number_field :taxrateone %>
  </div>

  <div class="field">
    <%= f.label :taxamountone %>
    <%= f.number_field :taxamountone %>
  </div>

  <div class="field">
    <%= f.label :taxtypetwo %>
    <%= f.number_field :taxtypetwo %>
  </div>

  <div class="field">
    <%= f.label :taxratetwo %>
    <%= f.number_field :taxratetwo %>
  </div>

  <div class="field">
    <%= f.label :taxamounttwo %>
    <%= f.number_field :taxamounttwo %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/invoice_line_items/edit.html.erb
<h1>Editing Invoice Line Item</h1>

<%= render 'form', invoice_line_item: @invoice_line_item %>

<%= link_to 'Show', @invoice_line_item %> |
<%= link_to 'Back', invoice_line_items_path %>

app/views/invoice_line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoice Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Item description</th>
      <th>Item unit cost</th>
      <th>Itam quantity</th>
      <th>Gross line total</th>
      <th>Discount amount</th>
      <th>Tax 1</th>
      <th>Tax 2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_line_items.each do |invoice_line_item| %>
      <tr>
        <td><%= invoice_line_item.item_name %></td>
        <td><%= invoice_line_item.item_description %></td>
        <td><%= invoice_line_item.item_unit_cost %></td>
        <td><%= invoice_line_item.itam_quantity %></td>
        <td><%= invoice_line_item.gross_line_total %></td>
        <td><%= invoice_line_item.discount_amount %></td>
        <td><%= invoice_line_item.tax_1 %></td>
        <td><%= invoice_line_item.tax_2 %></td>
        <td><%= link_to 'Show', invoice_line_item %></td>
        <td><%= link_to 'Edit', edit_invoice_line_item_path(invoice_line_item) %></td>
        <td><%= link_to 'Destroy', invoice_line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice Line Item', new_invoice_line_item_path %>

app/views/invoice_line_items/new.html.erb
<h1>New Invoice Line Item</h1>

<%= render 'form', invoice_line_item: @invoice_line_item %>

<%= link_to 'Back', invoice_line_items_path %>

app/views/invoice_line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @invoice_line_item.item_name %>
</p>

<p>
  <strong>Item description:</strong>
  <%= @invoice_line_item.item_description %>
</p>

<p>
  <strong>Item unit cost:</strong>
  <%= @invoice_line_item.item_unit_cost %>
</p>

<p>
  <strong>Itam quantity:</strong>
  <%= @invoice_line_item.itam_quantity %>
</p>

<p>
  <strong>Gross line total:</strong>
  <%= @invoice_line_item.gross_line_total %>
</p>

<p>
  <strong>Discount amount:</strong>
  <%= @invoice_line_item.discount_amount %>
</p>

<p>
  <strong>Net Total:</strong>
  <%= @invoice_line_item.net_total %>
</p>

<p>
  <strong>Tax Type:</strong>
  <%= @invoice_line_item.taxtypeone %>
</p>

<p>
  <strong>Tax Rate:</strong>
  <%= @invoice_line_item.taxrateone %>
</p>

<p>
  <strong>Tax Amount:</strong>
  <%= @invoice_line_item.taxamountone %>
</p>

<p>
  <strong>Tax Type:</strong>
  <%= @invoice_line_item.taxtypetwo %>
</p>

<p>
  <strong>Tax Rate:</strong>
  <%= @invoice_line_item.taxratetwo %>
</p>

<p>
  <strong>Tax Amount:</strong>
  <%= @invoice_line_item.taxamounttwo %>
</p>


<%= link_to 'Edit', edit_invoice_line_item_path(@invoice_line_item) %> |
<%= link_to 'Back', invoice_line_items_path %>