config/routes.rb
Rails.application.routes.draw do

  resources :expense_categories

  resources :expenses do
    resources :expense_categories do
    end
  end



  resources :invoices do
    resources :invoice_line_items 
  end
    



  resources :invoice_line_items
  resources :taxes

  resources :items do
    collection do
      post 'load_item_data'
      get 'duplicate_item'
    end
  end

  resources :contacts do
  end


  devise_for :users

  resources :companies do
    collection do
      post 'get_contacts_and_items'
    end
  end

  root 'welcome#index'


  devise_scope :user do
        get '/users/sign_out' => 'devise/sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get ':controller(/:action(/:id))(.:format)'

end
end

app/models/tax.rb
class Tax < ApplicationRecord

  scope :multiple, lambda { |ids_list| where("id in (?)", ids_list.is_a?(String) ? ids_list.split(',') : [*ids_list]) }
  scope :archive_multiple, lambda {|ids| multiple(ids).map(&:archive)}
  scope :delete_multiple, lambda {|ids| multiple(ids).map(&:destroy)}

  has_many :items
  belongs_to :user, optional: true
  belongs_to :company, optional: true
  has_many :invoice_line_items
  validates :name, :presence => true
  validates :percentage, :presence => true

  acts_as_archival
  acts_as_paranoid


  def self.is_exits? tax_name
    where(name: tax_name).present?
  end

  def self.recover_archived(ids)
    multiple(ids).each {|tax| tax.archive_number = nil; tax.archived_at = nil; tax.save}
  end

  def self.recover_deleted(ids)
    multiple(ids).only_deleted.each { |tax| tax.archive_number = nil; tax.archived_at = nil; tax.deleted_at = nil; tax.save }
  end

  def self.filter(params, per_page)
    mappings = {active: 'unarchived', archived: 'archived', deleted: 'only_deleted'}
    method = mappings[params[:status].to_sym]
    self.send(method).page(params[:page]).per(per_page)
  end

end

app/controllers/taxes_controller.rb
class TaxesController < ApplicationController
  before_action :authenticate_user!
 # before_action :set_tax, only: [:show, :edit, :update, :destroy]

  # GET /taxes
  # GET /taxes.json
  def index
    @taxes = current_user.current_company.taxes
  end

  # GET /taxes/1
  # GET /taxes/1.json
  def show
    @taxis = current_user.current_company.taxes.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @taxis }
    end
  end

  # GET /taxes/new
  def new
    @taxis = current_user.current_company.taxes.new
  end

  # GET /taxes/1/edit
  def edit
    @taxis = current_user.current_company.taxes.find(params[:id])
  end

  # POST /taxes
  # POST /taxes.json
  def create
    @taxis = current_user.current_company.taxes.new(taxes_params)

    respond_to do |format|
      if @taxis.save
        format.html { redirect_to @taxis, notice: 'Tax was successfully created.' }
        format.json { render :show, status: :created, location: @taxis }
      else
        format.html { render :new }
        format.json { render json: @taxis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taxes/1
  # PATCH/PUT /taxes/1.json
  def update
    @taxis = current_user.current_company.taxes.find(params[:id])
    respond_to do |format|
      if @taxis.update(taxes_params)
        format.html { redirect_to @taxes, notice: 'Tax was successfully updated.' }
        format.json { render :show, status: :ok, location: @tax }
      else
        format.html { render :edit }
        format.json { render json: @taxis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxes/1
  # DELETE /taxes/1.json
  def destroy
    @taxis = current_user.current_company.taxes.find(params[:id])
    @taxis.destroy
    respond_to do |format|
      format.html { redirect_to taxes_url, notice: 'Tax was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
#    def set_tax
 #     @tax = Tax.find(params[:id])
  #  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taxes_params
      params.require(:tax).permit(:name, :percentage)
    end
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/views/taxes/_form.html.erb
<%= form_for(@taxis, :html => {:novalidate => ""}) do |f| %>
  <% if @taxis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(taxis.errors.count, "error") %> prohibited this tax from being saved:</h2>

      <ul>
      <% taxis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :percentage %>
    <%= f.text_field :percentage %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taxes/edit.html.erb
<h1>Editing Tax</h1>

<%= render 'form', tax: @tax %>

<%= link_to 'Show', @tax %> |
<%= link_to 'Back', taxes_path %>

app/views/taxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Taxes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taxes.each do |taxis| %>
      <tr>
        <td><%= taxis.name %></td>
        <td><%= taxis.percentage %></td>
        <td><%= link_to 'Show', taxis %></td>
        <td><%#= link_to 'Edit', edit_tax_path(tax) %></td>
        <td><%#= link_to 'Destroy', tax, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tax', new_tax_path %>

app/views/taxes/new.html.erb
<h1>New Tax</h1>

<%= render 'form', tax: @tax %>

<%= link_to 'Back', taxes_path %>

app/views/taxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @taxis.name %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @taxis.percentage %>
</p>

<%= link_to 'Edit', edit_tax_path(@taxis) %> |
<%= link_to 'Back', taxes_path %>