config/routes.rb
Rails.application.routes.draw do

  resources :expense_categories

  resources :expenses do
    resources :expense_categories do
    end
  end



  resources :invoices do
    resources :invoice_line_items 
  end
    



  resources :invoice_line_items
  resources :taxes

  resources :items do
    collection do
      post 'load_item_data'
      get 'duplicate_item'
    end
  end

  resources :contacts do
  end


  devise_for :users

  resources :companies do
    collection do
      post 'get_contacts_and_items'
    end
  end

  root 'welcome#index'


  devise_scope :user do
        get '/users/sign_out' => 'devise/sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get ':controller(/:action(/:id))(.:format)'

end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = current_user.current_company.expenses
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @expense = current_user.current_company.expenses.find(params[:id])
 #   @contact = Contact.unscoped.find_by_id @expense.contact_id
#    @expense_category = ExpenseCategory.find(params[:id]) 
  end

  # GET /expenses/new
  def new
    @expense = current_user.current_company.expenses.new

    
  end

  # GET /expenses/1/edit
  def edit
    @expense = current_user.current_company.expenses.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = current_user.current_company.expenses.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    @expense = current_user.current_company.expenses.find(params[:id])
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:expense_amount, :expense_date, :expense_note, :taxtypeone, :taxrateone, :taxamountone, :taxtypetwo, :taxratetwo, :taxamounttwo, :expense_total, :expense_category_id, :contact_id, :company_id, :contact_company_name)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expenses.html.erb
<% if @expenses.length > 0 %>
    <% @expenses.each do |expense| %>
        <tr>
          <td class="align_center"><%= check_box_tag "expense_ids[]", expense.id, false, :id => "expense_#{expense.id}" %></td>
          <td class="align_left text-overflow-class" data-overflow-rows="2"><%= expense.expense_category.name %></td>
          <td class="align_left text-overflow-class" data-overflow-rows="2"><%= expense.contact.contact_company_name %></td>
          <td class="align_right text-overflow-class" data-overflow-rows="2"><%= number_to_indian_currency(expense.amount) %></td>
          <td class="align_center text-overflow-class" data-overflow-rows="2"><%=  expense.expense_date %></td>
          <td class="align_right text-overflow-class" data-overflow-rows="2"><%= number_to_indian_currency(expense.total) %></td>
          <td class="align_center">
          </td>
        </tr>
    <% end %>
<% else %>
    <tr>
      <td colspan="6">
        <div class="no_record_container">
          <%= no_record_message %>
        </div>
      </td>
    </tr>
<% end %>

app/views/expenses/_form.html.erb
<%= form_for @expense, :html => {:class => 'expense-form', :novalidate => ""} do |f| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field_row">
                  <div class="label_field left single"><%= f.label :expense_category_id, content_tag(:span, 'Category') %></div>
                  <div class="small_field">
                    <%= f.collection_select(:expense_category_id, ExpenseCategory.all, :id, :name, {:prompt => "", :include_blank => ""}, {"data-placeholder" => "Select a category...", :class => "expense_category small chzn-select", "data-form-container" => "clients_holder", "data-dropdown-width" => "130"})  %>
                  </div>
                </div>
                <!--field_row-->

                <div class="field_row description">
                  <div class="label_field left single"><%= f.label :contact_id, content_tag(:span, t('client')) %></div>
                  <div class="medium_field">
                    <%#= collection_select :invoice, :client_id, load_clients(action_name, @invoice.company_id) , :id, :organization_name, {:prompt => "", :include_blank => ""}, {"data-placeholder" => "Select a client...", :class => "invoice_client medium chzn-select", "data-form-container" => "clients_holder", "data-dropdown-width" => "300", :required => ""} %>
                    <% selected_contact = @contact.present? ? @contact.id : f.object.contact_id %>
                    <%= f.select :contact_id, options_from_collection_for_select(Contact.order('contact_first_name, contact_last_name'), :id, :contact_name,  selected_contact),  {:prompt => "", :include_blank => ""}, {"data-placeholder" => "Select a client...", :class => "expense_client medium chzn-select", "data-form-container" => "clients_holder", "data-dropdown-width" => "250"} %>
                    <ul class="field_description select">
                      <li><%= t('views.expenses.client_hint') %></li>

                    </ul>
                  </div>
                </div>


  <div class="field">
    <%= f.label :expense_amount %>
    <%= f.text_field :expense_amount %>
  </div>

  <div class="field">
    <%= f.label :expense_date %>
    <%= f.datetime_select :expense_date %>
  </div>

  <div class="field">
    <%= f.label :expense_note %>
    <%= f.text_field :expense_note %>
  </div>

  <div class="field">
    <%= f.label :taxtypeone %>
    <%= f.text_field :taxtypeone %>
  </div>

  <div class="field">
    <%= f.label :taxrateone %>
    <%= f.text_field :taxrateone %>
  </div>

  <div class="field">
    <%= f.label :taxamountone %>
    <%= f.text_field :taxamountone %>
  </div>

  <div class="field">
    <%= f.label :taxtypetwo %>
    <%= f.text_field :taxtypetwo %>
  </div>

  <div class="field">
    <%= f.label :taxratetwo %>
    <%= f.text_field :taxratetwo %>
  </div>

  <div class="field">
    <%= f.label :taxamounttwo %>
    <%= f.text_field :taxamounttwo %>
  </div>

  <div class="field">
    <%= f.label :expense_total %>
    <%= f.text_field :expense_total %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Expense amount</th>
      <th>Expense date</th>
      <th>Expense note</th>
      <th>Taxtypeone</th>
      <th>Taxrateone</th>
      <th>Taxamountone</th>
      <th>Taxtypetwo</th>
      <th>Taxratetwo</th>
      <th>Taxamounttwo</th>
      <th>Expense total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.expense_amount %></td>
        <td><%= expense.expense_date %></td>
        <td><%= expense.expense_note %></td>
        <td><%= expense.taxtypeone %></td>
        <td><%= expense.taxrateone %></td>
        <td><%= expense.taxamountone %></td>
        <td><%= expense.taxtypetwo %></td>
        <td><%= expense.taxratetwo %></td>
        <td><%= expense.taxamounttwo %></td>
        <td><%= expense.expense_total %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<%- model_class = Expense -%>

<p id="notice"><%= notice %></p>



        <p><%= @expense.expense_category.name %></p>


 <%= @expense.contact.contact_company_name %>
<p>
  <strong>Expense amount:</strong>
  <%= @expense.expense_amount %>
</p>

<p>
  <strong>Expense date:</strong>
  <%= @expense.expense_date %>
</p>

<p>
  <strong>Expense note:</strong>
  <%= @expense.expense_note %>
</p>

<p>
  <strong>Taxtypeone:</strong>
  <%= @expense.taxtypeone %>
</p>

<p>
  <strong>Taxrateone:</strong>
  <%= @expense.taxrateone %>
</p>

<p>
  <strong>Taxamountone:</strong>
  <%= @expense.taxamountone %>
</p>

<p>
  <strong>Taxtypetwo:</strong>
  <%= @expense.taxtypetwo %>
</p>

<p>
  <strong>Taxratetwo:</strong>
  <%= @expense.taxratetwo %>
</p>

<p>
  <strong>Taxamounttwo:</strong>
  <%= @expense.taxamounttwo %>
</p>

<p>
  <strong>Expense total:</strong>
  <%= @expense.expense_total %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>